[build]
  publish = "."               # root is the site folder

# 1-year cache for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options        = "DENY"
    X-XSS-Protection       = "1; mode=block"

# HTTP to HTTPS redirect
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# early-hint preloads
[[headers]]
  for = "/"
  [headers.values]
    Link = '</images/hero.jpg>; rel=preload; as=image, </fonts/Rubik-Regular.woff2>; rel=preload; as=font; type=font/woff2; crossorigin'